### ISSUE TITLE
edit rent needs cleaning

### ISSUE THREAD

**Issue by Sam-Morgan** [hezmondo/mjinn#38]
From the rent screen the user can edit the datecode / frequency and (seemingly) next rent date all independently of each other. datecode and next rent date should not be there.

It should also use validation to check that the user has entered ie a number in price/rent/arrears rather than a string.

**Comment by hezmondo** [comment]
I agreed with all that you say.  This might help:  

Next rent date is a derived value and is useful for the user to see everywhere that the user views the rent (home page, rent page, etc).  It can never be edited, because it does not exist until derived.

DateCode should and would be a derived value but for a unique and one off problem.  Ben has two rents with frequency = 2, both with the first rent date 30 Jun.  One has second rent date 30 Dec and the other 31 Dec and thus I came up with datecodes, to allow F2Jun30A and F2Jun30B.  If one of you clever maths geniuses can solve this single challenge, we can bin datecode completely.
