### ISSUE TITLE
Introduce caching of database queries

### ISSUE THREAD

**Issue by hezmondo** [hezmondo/mjinn#48]
My latest code uses this function at line 83 of app/main/common, to obtain 12 tuples, each containing 3 integer values:
    dates_m = get_dates_m()
What I really need is for this function to be run at startup, for the teeny object dates_m to be cached and for line 83 to get the cached object.  I found this flask advice rather confusing:

https://flask-caching.readthedocs.io/en/latest/

**Comment by jnbarchan** [comment]
Implemented **Flask-Caching**.  This allows us to cache the return results from specified functions, so that code will not re-issue a database fetch.

This has required the addition of a Flask module to **mjinn**'s requirements.  I have updated `mjinn README and start guide.md` to mention that we now need:
```
pip3 install flask-caching
```

**Comment by jnbarchan** [comment]
Hez asked me to rename `app/dao/utility.py` to `app/dao/common.py`.

And then merge in a bunch of functions, e.g. `def get_actypes()`, which just query all the rows from the tables holding "types".

Which then allows me to start putting `@cache.cached()` on them, to cache the static types tables.

I am doing that, and going through all the code using the cached tables where possible.

**Comment by hezmondo** [comment]
Let us close this issue while we decide which types tables might remain
